### ISSUE TITLE
Clothing rest pose mesh low poly count

### ISSUE THREAD

**Issue by HarryWang355** [PerceivingSystems/bedlam_clothing#2]
Hi authors, I noticed that the clothing meshes in the rest pose do not have high poly counts. This leads to many visible artifacts (like in the example image), making the mesh look less realistic. I'm wondering if there is a version with higher quality meshes, or if there is a way for me to generate higher quality meshes at a reasonable cost. Any suggestion would be greatly appreciated!
![19421729561187_ pic](https://github.com/user-attachments/assets/9fe2831a-b267-4c5c-9c4b-e3581efcc8d7)

**Comment by gfgb** [comment]
Hi,

The geometry of the clothing meshes is already quite dense. Increasing the number of vertices would make them much heavier to handle, and the size of the simulation caches would become much larger.

However, I think the issue here is mostly due to your visualization settings. 
In Blender, if you right-click on the mesh, you can select either "Shade Flat" or  "Shade Smooth".
By selecting "Shade Smooth" a better looking mesh will be rendered by interpolating the normals of the mesh between adjacent faces, and you will get a better looking result.
